import type { Metadata } from 'next';
import './globals.css';
import { NavBar } from '@/components/AppBar';


export const metadata: Metadata = {
  title: 'Eagle Online Tool',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-battleship flex flex-col min-h-screen">
        <NavBar/>
        <main className='p-8 h-full mt-20'>
          {children}
        </main>
      </body>
    </html>
  );
};
